version: '3.8'

services:
  frontend:
    container_name: parefi-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - parefi-network
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  backend:
    container_name: parefi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - parefi-network
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: sh -c "npx prisma generate && npx ts-node src/index.ts"

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - parefi-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - parefi-network
    depends_on:
      - postgres

networks:
  parefi-network:
    driver: bridge
